name: CI

on: pull_request

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1-dev.yaml
        esphome-version:
          - stable
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: ${{ matrix.file }}
          version: ${{ matrix.esphome-version }}
            - name: Upload artifact
      - name: upload build
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ steps.esphome-build.outputs.name }}
          path: output
