name: Manual Build

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Config to use'
        required: true
        default: 'Halo-v1'

jobs:
  build:
    name: Building ${{ input.config }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: Halo (${{ inputs.config }})
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/${{ inputs.config }}.yaml
